global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dropshipping-monitor'

# 알림 규칙 파일
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# AlertManager 설정
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# 스크래핑 대상
scrape_configs:
  # API 서버 메트릭
  - job_name: 'dropshipping-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/api/v1/monitoring/metrics'
    scrape_interval: 10s

  # Node Exporter (호스트 메트릭)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx Exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # 컨테이너 메트릭 (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Prometheus 자체
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']